# For more information: https://laravel.com/docs/sail
services:
    application_ci:
        build:
            context: ./docker/php/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: laravel-ddd-ecommerce
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            DB_CONNECTION: pgsql
            DB_DATABASE: postgres
            DB_USERNAME: postgres
            DB_HOST: database_ci
            REDIS_HOST: redis_ci
        volumes:
            - '.:/var/www/html'
        networks:
            - sail_ci
        depends_on:
            - database_ci
            - redis_ci
        command: [ "make", "install", "lint", "analyse", "test-coverage" ]
    database_ci:
        image: 'postgres:14.2-alpine'
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]
            retries: 3
            timeout: 5s
        networks:
            - sail_ci
    redis_ci:
        image: 'redis:6.2.6-alpine'
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            retries: 3
            timeout: 5s
        networks:
            - sail_ci

networks:
    sail_ci:
        driver: bridge
