# For more information: https://laravel.com/docs/sail
services:
    application_test:
        build:
            context: ./docker/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: laravel-ddd-ecommerce
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sail_test
        depends_on:
            - database_test
            - redis_test
    database_test:
        image: 'postgres:14.1'
        ports:
            - '${FORWARD_TEST_DB_PORT:-5433}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        networks:
            - sail_test
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]
            retries: 3
            timeout: 5s
    redis_test:
        image: 'redis:6.2.6-alpine'
        ports:
            - '${FORWARD_TEST_REDIS_PORT:-6379}:6379'
        networks:
            - sail_test
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            retries: 3
            timeout: 5s

networks:
    sail_test:
        driver: bridge
