# For more information: https://laravel.com/docs/sail
services:
    application_ci:
        extends:
            file: docker-compose.yml
            service: application
        environment:
            DB_HOST: database_ci
            REDIS_HOST: redis_ci
            XDEBUG_MODE: ${SAIL_XDEBUG_MODE}
        depends_on:
            database_ci:
                condition: service_healthy
            redis_ci:
                condition: service_healthy
            elasticsearch_ci:
                condition: service_healthy
        command: >
            make install lint analyse test-coverage
        networks:
            - sail_ci

    database_ci:
        extends:
            file: docker-compose.yml
            service: database
        image: postgis/postgis:${POSTGRES_VERSION}-alpine
        networks:
            - sail_ci

    redis_ci:
        extends:
            file: docker-compose.yml
            service: redis
        image: redis:${REDIS_VERSION}-alpine
        networks:
            - sail_ci

    elasticsearch_ci:
        extends:
            file: docker-compose.yml
            service: elasticsearch
        networks:
            - sail_ci

networks:
    sail_ci:
        driver: bridge
