# For more information: https://laravel.com/docs/sail
services:
    application_ci:
        extends:
            file: docker-compose.yml
            service: application
        environment:
            DB_HOST: database_ci
            REDIS_HOST: redis_ci
            ELASTICSEARCH_URL: http://elasticsearch_ci:9200
            XDEBUG_MODE: ${SAIL_XDEBUG_MODE}
            APPLICATION_COMPOSER_CACHE: ${APPLICATION_COMPOSER_CACHE:-false}
        depends_on:
            database_ci:
                condition: service_started
            redis_ci:
                condition: service_started
            elasticsearch_ci:
                condition: service_started
        command:
            - bash
            - -c
            - |
                make prepare lint deptrac insights analyse
                dockerize -wait tcp://database_ci:5432 -wait tcp://redis_ci:6379 -wait tcp://elasticsearch_ci:9200 -timeout 15s
                make test-coverage
        networks:
            - sail_ci

    database_ci:
        extends:
            file: docker-compose.yml
            service: database
        image: postgis/postgis:${POSTGRES_VERSION}-alpine
        networks:
            - sail_ci

    redis_ci:
        extends:
            file: docker-compose.yml
            service: redis
        image: redis:${REDIS_VERSION}-alpine
        networks:
            - sail_ci

    elasticsearch_ci:
        extends:
            file: docker-compose.yml
            service: elasticsearch
        networks:
            - sail_ci

networks:
    sail_ci:
        driver: bridge
