# For more information: https://laravel.com/docs/sail
services:
    application_test:
        extends:
            file: docker-compose.yml
            service: application
        environment:
            DB_HOST: database_test
            REDIS_HOST: redis_test
            ELASTICSEARCH_URL: http://elasticsearch_test:9200
            XDEBUG_MODE: ${SAIL_XDEBUG_MODE}
        depends_on:
            database_test:
                condition: service_healthy
            redis_test:
                condition: service_healthy
            elasticsearch_test:
                condition: service_healthy
        networks:
            - sail_test

    database_test:
        extends:
            file: docker-compose.yml
            service: database
        image: postgis/postgis:${POSTGRES_VERSION}-alpine
        ports:
            - ${FORWARD_TEST_DB_PORT}:5432
        networks:
            - sail_test

    redis_test:
        extends:
            file: docker-compose.yml
            service: redis
        image: redis:${REDIS_VERSION}-alpine
        networks:
            - sail_test

    elasticsearch_test:
        extends:
            file: docker-compose.yml
            service: elasticsearch
        networks:
            - sail_test

networks:
    sail_test:
        driver: bridge
