# For more information: https://laravel.com/docs/sail
services:
    application_test:
        build:
            context: './docker/php/${PHP_VERSION}'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: '${APPLICATION_IMAGE:-laravel-ddd-ecommerce}'
        environment:
            WWWUSER: '${WWWUSER}'
            PHP_VERSION: '${PHP_VERSION}'
            LARAVEL_SAIL: 1
            DB_HOST: database_test
            REDIS_HOST: redis_test
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail_test
        depends_on:
            - database_test
            - redis_test

    database_test:
        image: 'postgres:${POSTGRES_VERSION}-alpine'
        ports:
            - '${FORWARD_TEST_DB_PORT:-5433}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_VERSION: '${POSTGRES_VERSION}'
        networks:
            - sail_test
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]
            retries: 3
            timeout: 5s

    redis_test:
        image: 'redis:${REDIS_VERSION}-alpine'
        ports:
            - '${FORWARD_TEST_REDIS_PORT:-6379}:6379'
        environment:
            REDIS_VERSION: '${REDIS_VERSION}'
        networks:
            - sail_test
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            retries: 3
            timeout: 5s

networks:
    sail_test:
        driver: bridge
