name: "@domains/users"
description: "Users Domain"
namespace: "App\\Domains\\Users\\"

# "Public API" of the modulite: classes, functions, constants, etc.
# Symbols not listed here will be internal.
export:
    - "Admin\\Resources\\UserResource"
    - "Database\\Seeders\\UserSeeder"
    - "Events\\EmailVerificationFailed"
    - "Events\\EmailVerificationSucceeded"
    - "Events\\Login"
    - "Events\\Logout"
    - "Events\\Registered"
    - "Http\\Resources\\UserResource"
    - "Models\\User"

# Dependencies: other modulites, global classes, defines, etc.
require:
    - "@components/addressable"
    - "@components/login-historyable"
    - "@domains/admin"
    - "@domains/cart"
    - "@domains/common"
    - "@domains/feedback"
    - "@infrastructure"
    - "@interfaces"
    - "#babenkoivan/elastic-migrations"
    - "#babenkoivan/elastic-scout-driver-plus"
    - "#filament/filament"
    - "#filament/forms"
    - "#filament/tables"
    - "#flowframe/laravel-trend"
    - "#illuminate/collections"
    - "#illuminate/contracts"
    - "#illuminate/database"
    - "#illuminate/http"
    - "#illuminate/notifications"
    - "#illuminate/routing"
    - "#illuminate/support"
    - "#illuminate/testing"
    - "#laravel/framework"
    - "#laravel/sanctum"
    - "#nesbot/carbon"
    - "#phpoffice/phpspreadsheet"
    - "#torann/geoip"
    - "#spatie/laravel-query-builder"
    - "#symfony/http-foundation"
    - "#symfony/http-kernel"
    - "#ysfkaya/filament-phone-input"
