name: "@domains/catalog"
description: "Catalog Domain"
namespace: "App\\Domains\\Catalog\\"

# "Public API" of the modulite: classes, functions, constants, etc.
# Symbols not listed here will be internal.
export:
    - "Admin\\Pages\\ManageCatalogSettings"
    - "Admin\\Resources\\ProductCategoryResource"
    - "Admin\\Resources\\ProductResource"
    - "Database\\Seeders\\ProductAttributeValueSeeder"
    - "Database\\Seeders\\ProductCategorySeeder"
    - "Database\\Seeders\\ProductPriceSeeder"
    - "Database\\Seeders\\ProductSeeder"
    - "Enums\\Translation\\AdminNavigationGroupTranslationKey"
    - "Http\\Resources\\ProductCategory\\HeavyProductCategoryResource"
    - "Http\\Resources\\ProductCategory\\LightProductCategoryResource"
    - "Http\\Resources\\ProductCategory\\MediumProductCategoryResource"
    - "Http\\Resources\\Product\\HeavyProductResource"
    - "Http\\Resources\\Product\\LightProductResource"
    - "Http\\Resources\\Product\\ProductResource"
    - "Models\\Pivot\\ProductProductCategory"
    - "Models\\Product"
    - "Models\\ProductCategory"
    - "Models\\Settings\\CatalogSettings"

# Dependencies: other modulites, global classes, defines, etc.
require:
    - "@application"
    - "@components/attributable"
    - "@components/mediable"
    - "@components/purchasable"
    - "@components/queryable"
    - "@domains/admin"
    - "@domains/common"
    - "@domains/feedback"
    - "@infrastructure"
    - "@interfaces"
    - "#akaunting/laravel-money"
    - "#babenkoivan/elastic-scout-driver-plus"
    - "#babenkoivan/elastic-migrations"
    - "#colinodell/json5" # Bug - JSON_THROW_ON_ERROR
    - "#illuminate/collections"
    - "#filament/filament"
    - "#filament/forms"
    - "#filament/notifications"
    - "#filament/tables"
    - "#illuminate/console"
    - "#illuminate/database"
    - "#illuminate/http"
    - "#illuminate/routing"
    - "#illuminate/support"
    - "#illuminate/validation"
    - "#laravel/framework"
    - "#nesbot/carbon"
    - "#phpoffice/phpspreadsheet"
    - "#spatie/laravel-medialibrary"
    - "#spatie/laravel-query-builder"
    - "#spatie/laravel-settings"
    - "#spatie/laravel-sluggable"
    - "#stevebauman/purify"
