name: "@domains/common"
description: "Common Domain"
namespace: "App\\Domains\\Common\\"

# "Public API" of the modulite: classes, functions, constants, etc.
# Symbols not listed here will be internal.
export:
    - "Classes\\Excel\\ExportColumn"
    - "Console\\Commands\\RefreshApplicationCommand"
    - "Database\\Builders\\ConfirmationTokenBuilder"
    - "Database\\Seeders\\DatabaseSeeder"
    - "Database\\Factory"
    - "Database\\Seeder"
    - "Enums\\BooleanString"
    - "Enums\\ConfirmationTokenType"
    - "Enums\\Lang\\TranslationFilename"
    - "Enums\\QueueName"
    - "Enums\\Response\\ResponseKey"
    - "Enums\\Response\\ResponseValueType"
    - "Enums\\ServiceProviderNamespace"
    - "Exceptions\\HttpException"
    - "Exceptions\\InvalidConfirmationTokenException"
    - "Exceptions\\NotSupportedClassException"
    - "Http\\Middleware\\AddTimestamp"
    - "Http\\Middleware\\AddUserToSentryScope"
    - "Http\\Middleware\\ForceJsonResponse"
    - "Http\\Middleware\\Recaptcha"
    - "Http\\Requests\\IndexRequest"
    - "Interfaces\\Exportable"
    - "Jobs\\ExportJob"
    - "Models\\ConfirmationToken"
    - "Services\\Repositories\\ConfirmationTokenRepository"
    - "Tests\\MocksGeoIPRequests"
    - "Tests\\TestApplicationState"
    - "Tests\\TestCase"
    - "Traits\\Models\\HasExtendedFunctionality"
    - "Traits\\Models\\Searchable"
    - "Utils\\AppUtils"
    - "Utils\\ClassUtils"
    - "Utils\\FileUtils"
    - "Utils\\LangUtils"
    - "Utils\\MathUtils"
    - "Utils\\PathUtils"
    - "Utils\\StringUtils"

# Dependencies: other modulites, global classes, defines, etc.
require:
    - "@application"
    - "@components/attributable"
    - "@components/queryable"
    - "@domains/admin"
    - "@domains/catalog"
    - "@domains/feedback"
    - "@domains/news"
    - "@domains/users"
    - "@infrastructure"
    - "#akaunting/laravel-money"
    - "#babenkoivan/elastic-migrations"
    - "#illuminate/auth"
    - "#illuminate/cache"
    - "#illuminate/collections"
    - "#illuminate/console"
    - "#illuminate/contracts"
    - "#illuminate/database"
    - "#illuminate/events"
    - "#illuminate/filesystem"
    - "#illuminate/http"
    - "#illuminate/routing"
    - "#illuminate/support"
    - "#illuminate/testing"
    - "#laravel/framework"
    - "#laravel/scout"
    - "#maatwebsite/excel"
    - "#nesbot/carbon"
    - "#phpoffice/phpspreadsheet"
    - "#sentry/sentry"
    - "#symfony/http-foundation"
    - "#torann/geoip"
