name: "@components/addressable"
description: "Addresses-related Stuff"
namespace: "App\\Components\\Addressable\\"

# "Public API" of the modulite: classes, functions, constants, etc.
# Symbols not listed here will be internal.
export:
    - "Admin\\RelationManagers\\AddressesRelationManager"
    - "Models\\Address"

# Dependencies: other modulites, global classes, defines, etc.
require:
    - "@domains/admin"
    - "@domains/common"
    - "@infrastructure"
    - "#filament/filament"
    - "#filament/forms"
    - "#filament/tables"
    - "#illuminate/database"
    - "#illuminate/support"
    - "#squirephp/countries"
    - "#squirephp/regions"
