name: "@domains/admin"
description: "Admin Domain"
namespace: "App\\Domains\\Admin\\"

# "Public API" of the modulite: classes, functions, constants, etc.
# Symbols not listed here will be internal.
export:
    - "Admin\\Abstracts\\Pages\\CreateRecord"
    - "Admin\\Abstracts\\Pages\\EditRecord"
    - "Admin\\Abstracts\\Pages\\ListRecords"
    - "Admin\\Abstracts\\Pages\\ViewRecord"
    - "Admin\\Abstracts\\RelationManager"
    - "Admin\\Abstracts\\Resource"
    - "Admin\\Abstracts\\SettingsPage"
    - "Admin\\Abstracts\\SimpleResource"
    - "Admin\\Components\\Actions\\UpdateBulkAction"
    - "Admin\\Components\\Cards\\TimestampsCard"
    - "Admin\\Components\\Forms\\RichEditor"
    - "Database\\Seeders\\AdminSeeder"
    - "Enums\\Translation\\AdminNavigationGroupTranslationKey"
    - "Enums\\Translation\\AdminPagePropertyTranslationKey"
    - "Enums\\Translation\\AdminRelationPropertyTranslationKey"
    - "Enums\\Translation\\AdminResourcePropertyTranslationKey"
    - "Enums\\Translation\\AdminWidgetPropertyTranslationKey"
    - "Models\\Admin"
    - "Tests\\AdminCrudTestCase"
    - "Tests\\AdminExportTest"
    - "Tests\\AdminTestCase"
    - "Traits\\Translation\\TranslatableAdminWidget"

# Dependencies: other modulites, global classes, defines, etc.
require:
    - "@components/attributable"
    - "@components/login-historyable"
    - "@domains"
    - "@domains/catalog"
    - "@domains/common"
    - "@domains/feedback"
    - "@domains/news"
    - "@domains/users"
    - "@infrastructure"
    - "#filament/filament"
    - "#filament/forms"
    - "#filament/support"
    - "#filament/tables"
    - "#filament/spatie-laravel-settings-plugin"
    - "#illuminate/collections"
    - "#illuminate/contracts"
    - "#illuminate/database"
    - "#illuminate/http"
    - "#illuminate/routing"
    - "#illuminate/support"
    - "#itsgoingd/clockwork"
    - "#laravel/framework"
    - "#livewire/livewire"
    - "#maatwebsite/excel"
