# Name of workflow
name: PHP CI

# Trigger the workflow on push or pull request
on:
    - push
    - pull_request

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@main

            -   name: Cache Docker images
                uses: satackey/action-docker-layer-caching@main-release
                continue-on-error: true

            -   name: Get Composer cache directory
                id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"

                # https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows
            -   name: Cache Composer dependencies
                uses: actions/cache@main
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: composer-

            -   name: Cache PHPStan analysis
                uses: actions/cache@main
                with:
                    path: build/phpstan
                    key: php-8.1-phpstan-${{ github.sha }}
                    restore-keys: php-8.1-phpstan-

            -   name: Run CI
                run: make ci

            -   name: Upload Coverage to CodeCov.io
                uses: codecov/codecov-action@master
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
                    file: build/logs/clover.xml
                    fail_ci_if_error: true
