# Name of workflow
name: PHP CI

# Trigger the workflow on push or pull request
on:
    - push
    - pull_request

jobs:
    build:
        runs-on: ubuntu-latest
        environment: CI
        steps:
            -   uses: actions/checkout@main

            -   name: Set Up Docker Buildx
                id: buildx
                uses: docker/setup-buildx-action@master

            -   name: Login to Docker Hub
                uses: docker/login-action@master
                with:
                    username: ${{ secrets.DOCKER_HUB_USERNAME }}
                    password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            -   name: Get Current Branch
                id: current-branch
                run: echo "CURRENT_BRANCH=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT

            -   name: Set APPLICATION_IMAGE Env Variable
                run: echo "APPLICATION_IMAGE=$(echo "${{ secrets.APPLICATION_IMAGE_REPOSITORY }}:${{ steps.current-branch.outputs.CURRENT_BRANCH == 'master' && 'latest' || steps.current-branch.outputs.CURRENT_BRANCH }}")" >> $GITHUB_ENV

            -   name: Docker Build && Push
                uses: docker/build-push-action@master
                with:
                    context: ./docker/php/
                    builder: ${{ steps.buildx.outputs.name }}
                    push: true
                    tags: ${{ env.APPLICATION_IMAGE }}
                    cache-from: type=gha
                    cache-to: type=gha,mode=max
                    build-args: WWWGROUP=1000

                # https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows

            -   name: Get Composer Cache Directory
                id: composer-cache
                run: echo "COMPOSER_CACHE_DIR=$(composer config vendor-dir)" >> $GITHUB_OUTPUT

            -   name: Cache Composer Dependencies
                uses: actions/cache@main
                with:
                    path: ${{ steps.composer-cache.outputs.COMPOSER_CACHE_DIR }}
                    key: composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: composer-

            -   name: Cache PHPStan Analysis
                uses: actions/cache@main
                with:
                    path: storage/phpstan
                    key: php-8.1-phpstan-${{ github.sha }}
                    restore-keys: php-8.1-phpstan-

            -   name: Cache Laravel Pint Analysis
                uses: actions/cache@main
                with:
                    path: storage/pint
                    key: pint-${{ github.sha }}
                    restore-keys: pint-

            -   name: Run CI
                run: make ci
                env:
                    APPLICATION_IMAGE: ${{ env.APPLICATION_IMAGE }}

            -   name: Upload Coverage to CodeCov.io
                uses: codecov/codecov-action@main
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
                    file: storage/logs/clover.xml
                    fail_ci_if_error: true
