# Name of workflow
name: PHP CI

# Trigger the workflow on push or pull request
on:
    - push
    - pull_request

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@main

            # In this step, this action saves a list of existing images,
            # the cache is created without them in the post run.
            # It also restores the cache if it exists.
            -   uses: satackey/action-docker-layer-caching@main-release
                # Ignore the failure of a step and avoid terminating the job.
                continue-on-error: true

            -   name: Run CI
                run: make ci

            -   name: Upload Coverage to CodeCov.io
                uses: codecov/codecov-action@master
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
                    file: build/logs/clover.xml
                    fail_ci_if_error: true
