# Name of workflow
name: PHP CI

# Trigger the workflow on push or pull request
on:
    - push
    - pull_request

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@master

            -   name: Run CI
                run: make ci

            -   name: Upload Coverage to CodeCov.io
                uses: codecov/codecov-action@master
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
                    file: build/logs/clover.xml
                    fail_ci_if_error: true
